format = '''
$time$directory$git_branch[](fg:bright-black) 
 [󱞩 ](bold)
'''

right_format = """
"""

command_timeout = 1000

# Disable the blank line at the start of the prompt
add_newline = true

[username]
show_always = true
style_user = "white"
style_root = "red"
format = '[]($style)[$user](bold bg:$style fg:black)[](bg:bright-black fg:$style)'
disabled = false

[directory]
style = "bg:bright-black fg:black"
format = "[ $path]($style)"
repo_root_style = "bold bg:bright-black fg:black"
repo_root_format = "[ $before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style)"
truncation_length = 3
truncate_to_repo = true
# truncation_symbol = "…/"

[time]
disabled = false
time_format = "%R"
style = "white"
format = '[]($style)[$time](bold bg:$style fg:black)[](bg:bright-black fg:$style)'

[git_branch]
symbol = ""
style = "bg:bright-black fg:black"
format = '[  $symbol $branch]($style)'
